# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 03:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7535\u8bdd')),
                ('group', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7528\u6237\u7ec4')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7c7b\u578b')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u72b6\u6001')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7535\u8bdd')),
                ('tell', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7535\u8bdd')),
                ('pnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cloud.UserInfo', verbose_name='\u7236\u8282\u70b9')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
