# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-26 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u540d\u79f0')),
                ('certificate', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u8bc1\u4e66')),
                ('specifications', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u89c4\u683c')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='\u6210\u672c')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u63cf\u8ff0')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u72b6\u6001')),
                ('creatdate', models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatedate', models.DateTimeField(blank=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='ClientHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientGUID', models.CharField(max_length=50, null=True, verbose_name='GUID')),
                ('clientName', models.CharField(max_length=200, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('owernID', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7528\u6237GUID')),
                ('hostType', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4e3b\u673a\u7c7b\u578b')),
                ('vendor', models.CharField(blank=True, max_length=1000, null=True, verbose_name='vendor')),
                ('zone', models.CharField(blank=True, max_length=1000, null=True, verbose_name='zone')),
                ('clientID', models.IntegerField(blank=True, null=True, verbose_name='\u4e3b\u673aID')),
                ('proxyClientID', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u4ee3\u7406\u4e3b\u673a\u5217\u8868')),
                ('creditInfo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u8ba4\u8bc1\u4fe1\u606f')),
                ('agentTypeList', models.CharField(blank=True, max_length=2000, null=True, verbose_name='\u4ee3\u7406\u7c7b\u578b\u5217\u8868')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u72b6\u6001')),
                ('platform', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5e73\u53f0')),
                ('appGroup', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5e94\u7528\u7ec4')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u63cf\u8ff0')),
                ('installTime', models.DateTimeField(blank=True, null=True, verbose_name='\u5b89\u88c5\u65f6\u95f4')),
                ('activeTime', models.DateTimeField(blank=True, null=True, verbose_name='\u6fc0\u6d3b\u65f6\u95f4')),
                ('firstProtectTime', models.DateTimeField(blank=True, null=True, verbose_name='\u9996\u6b21\u4fdd\u62a4\u65f6\u95f4')),
                ('lastProtectTime', models.DateTimeField(blank=True, null=True, verbose_name='\u6700\u8fd1\u4fdd\u62a4\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u540d\u79f0')),
                ('certificate', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u8bc1\u4e66')),
                ('specifications', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u89c4\u683c')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='\u6210\u672c')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u63cf\u8ff0')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u72b6\u6001')),
                ('creatdate', models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatedate', models.DateTimeField(blank=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataSetGUID', models.CharField(max_length=50, null=True, verbose_name='GUID')),
                ('clientGUID', models.CharField(max_length=50, null=True, verbose_name='\u4e3b\u673aGUID')),
                ('clientName', models.CharField(max_length=200, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('owernID', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7528\u6237GUID')),
                ('vendor', models.CharField(blank=True, max_length=1000, null=True, verbose_name='vendor')),
                ('zone', models.CharField(blank=True, max_length=1000, null=True, verbose_name='zone')),
                ('clientID', models.IntegerField(blank=True, null=True, verbose_name='\u4e3b\u673aID')),
                ('instanceName', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5b9e\u4f8b\u540d\u79f0')),
                ('agentType', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4ee3\u7406\u7c7b\u578b')),
                ('credit', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u8ba4\u8bc1\u4fe1\u606f')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u72b6\u6001')),
                ('appGroup', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5e94\u7528\u7ec4\u540d\u79f0')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u63cf\u8ff0')),
                ('content', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u4fdd\u62a4\u5185\u5bb9')),
                ('installTime', models.DateTimeField(blank=True, null=True, verbose_name='\u5b89\u88c5\u65f6\u95f4')),
                ('activeTime', models.DateTimeField(blank=True, null=True, verbose_name='\u6fc0\u6d3b\u65f6\u95f4')),
                ('firstProtectTime', models.DateTimeField(blank=True, null=True, verbose_name='\u9996\u6b21\u4fdd\u62a4\u65f6\u95f4')),
                ('lastProtectTime', models.DateTimeField(blank=True, null=True, verbose_name='\u6700\u8fd1\u4fdd\u62a4\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u540d\u79f0')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7c7b\u578b')),
                ('supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4f9b\u5e94\u5546')),
                ('certificate', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u8bc1\u4e66')),
                ('specifications', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u89c4\u683c')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u63cf\u8ff0')),
                ('level', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u7ea7\u522b')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u72b6\u6001')),
                ('creatdate', models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatedate', models.DateTimeField(blank=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='SchduleResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u540d\u79f0')),
                ('certificate', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u8bc1\u4e66')),
                ('specifications', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u89c4\u683c')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='\u6210\u672c')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u63cf\u8ff0')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u72b6\u6001')),
                ('creatdate', models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatedate', models.DateTimeField(blank=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.ResourcePool')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='forgetpassword',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4fee\u6539\u5bc6\u7801\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userGUID',
            field=models.CharField(max_length=50, null=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u516c\u53f8'),
        ),
        migrations.AddField(
            model_name='computerresource',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.ResourcePool'),
        ),
        migrations.AddField(
            model_name='backupresource',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.ResourcePool'),
        ),
    ]
