# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20161126_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u540d\u79f0')),
                ('certificate', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u8bc1\u4e66')),
                ('specifications', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u89c4\u683c')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='\u6210\u672c')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u63cf\u8ff0')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u72b6\u6001')),
                ('creatdate', models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatedate', models.DateTimeField(blank=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.ResourcePool')),
            ],
        ),
    ]
