# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_vmresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorGUID', models.CharField(max_length=50, null=True, verbose_name='GUID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u540d\u79f0')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7c7b\u578b')),
                ('content', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u5185\u5bb9')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u72b6\u6001')),
            ],
        ),
    ]
