# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joblist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField(verbose_name='\u4efb\u52a1ID')),
                ('appid', models.IntegerField(blank=True, null=True)),
                ('jobinitfrom', models.CharField(blank=True, max_length=200, null=True)),
                ('clientname', models.CharField(blank=True, max_length=200, null=True)),
                ('idataagent', models.CharField(blank=True, max_length=200, null=True)),
                ('instance', models.CharField(blank=True, max_length=200, null=True)),
                ('backupset', models.CharField(blank=True, max_length=200, null=True)),
                ('subclient', models.CharField(blank=True, max_length=200, null=True)),
                ('data_sp', models.CharField(blank=True, max_length=50, null=True)),
                ('backuplevelInt', models.IntegerField(blank=True, null=True)),
                ('backuplevel', models.CharField(blank=True, max_length=200, null=True)),
                ('incrlevel', models.IntegerField(blank=True, null=True)),
                ('jobstatusInt', models.IntegerField(blank=True, null=True)),
                ('jobstatus', models.CharField(blank=True, max_length=200, null=True)),
                ('jobfailedreason', models.CharField(blank=True, max_length=5000, null=True)),
                ('transferTime', models.IntegerField(blank=True, null=True)),
                ('startdateunixsec', models.BigIntegerField(blank=True, null=True)),
                ('enddateunixsec', models.BigIntegerField(blank=True, null=True)),
                ('startdate', models.DateTimeField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('enddate', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('durationunixsec', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('numstreams', models.IntegerField(blank=True, null=True)),
                ('numbytesuncomp', models.BigIntegerField(blank=True, null=True)),
                ('numbytescomp', models.BigIntegerField(blank=True, null=True)),
                ('numobjects', models.BigIntegerField(blank=True, null=True)),
                ('isAged', models.IntegerField(blank=True, null=True)),
                ('isAgedStr', models.CharField(blank=True, max_length=20, null=True)),
                ('xmlJobOptions', models.CharField(blank=True, max_length=5000, null=True)),
                ('retentionDays', models.CharField(blank=True, max_length=200, null=True)),
                ('systemStateBackup', models.IntegerField(blank=True, null=True)),
                ('inPrimaryCopy', models.IntegerField(blank=True, null=True)),
                ('failedobjects', models.IntegerField(blank=True, null=True)),
                ('totalBackupSize', models.BigIntegerField(blank=True, null=True)),
                ('encrypted', models.CharField(blank=True, max_length=200, null=True)),
                ('diskcapacity', models.BigIntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
