# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-18 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_joblist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vmresource',
            options={'verbose_name': '虚机资源', 'verbose_name_plural': '虚机资源'},
        ),
        migrations.RemoveField(
            model_name='vmresource',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='vmresource',
            name='cost',
        ),
        migrations.AddField(
            model_name='vmresource',
            name='system',
            field=models.CharField(blank=True, max_length=50, verbose_name='系统'),
        ),
        migrations.AddField(
            model_name='vmresource',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.VmResource', verbose_name='模板'),
        ),
        migrations.AddField(
            model_name='vmresource',
            name='template_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='模板名称'),
        ),
        migrations.AddField(
            model_name='vmresource',
            name='uuid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='uuid'),
        ),
        migrations.AddField(
            model_name='vmresource',
            name='vm_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='虚机数'),
        ),
        migrations.AddField(
            model_name='vmresource',
            name='vm_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='虚机类型'),
        ),
    ]
