# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-02 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_workfolwstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='预案编号')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='预案名称')),
                ('remark', models.CharField(blank=True, max_length=5000, null=True, verbose_name='预案描述')),
                ('sign', models.CharField(blank=True, max_length=20, null=True, verbose_name='是否签到')),
                ('rto', models.IntegerField(blank=True, null=True, verbose_name='RTO')),
                ('rpo', models.IntegerField(blank=True, null=True, verbose_name='RPO')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='步骤编号')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='步骤名称')),
                ('approval', models.CharField(blank=True, max_length=10, null=True, verbose_name='是否审批')),
                ('skip', models.CharField(blank=True, max_length=10, null=True, verbose_name='能否跳过')),
                ('group', models.CharField(blank=True, max_length=50, null=True, verbose_name='角色')),
                ('time', models.IntegerField(blank=True, null=True, verbose_name='预计耗时')),
                ('state', models.CharField(blank=True, max_length=10, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Process')),
            ],
        ),
        migrations.DeleteModel(
            name='workfolwstep',
        ),
    ]
