# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-02 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0012_workfolwstep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workfolwstep',
        ),
    ]
