# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-15 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0013_delete_workfolwstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='脚本编号')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='主机IP')),
                ('port', models.CharField(blank=True, max_length=10, null=True, verbose_name='端口号')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='连接类型')),
                ('runtype', models.CharField(blank=True, max_length=20, null=True, verbose_name='运行类型')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='密码')),
                ('filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='脚本文件名')),
                ('paramtype', models.CharField(blank=True, max_length=20, null=True, verbose_name='参数类型')),
                ('param', models.CharField(blank=True, max_length=100, null=True, verbose_name='脚本参数')),
                ('scriptpath', models.CharField(blank=True, max_length=100, null=True, verbose_name='脚本文件路径')),
                ('runpath', models.CharField(blank=True, max_length=100, null=True, verbose_name='执行路径')),
                ('command', models.CharField(blank=True, max_length=500, null=True, verbose_name='生产命令行')),
                ('maxtime', models.IntegerField(blank=True, null=True, verbose_name='超时时间')),
                ('time', models.IntegerField(blank=True, null=True, verbose_name='预计耗时')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.Step')),
            ],
        ),
    ]
