# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-22 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0015_auto_20180622_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processrun',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processtask',
            name='processrun',
        ),
        migrations.RemoveField(
            model_name='processtask',
            name='steprun',
        ),
        migrations.RemoveField(
            model_name='scriptrun',
            name='script',
        ),
        migrations.RemoveField(
            model_name='scriptrun',
            name='steprun',
        ),
        migrations.RemoveField(
            model_name='steprun',
            name='processrun',
        ),
        migrations.RemoveField(
            model_name='steprun',
            name='step',
        ),
        migrations.DeleteModel(
            name='ProcessRun',
        ),
        migrations.DeleteModel(
            name='ProcessTask',
        ),
        migrations.DeleteModel(
            name='ScriptRun',
        ),
        migrations.DeleteModel(
            name='StepRun',
        ),
    ]
