# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-28 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0018_process_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='last',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='cloud.Step', verbose_name='上一步'),
        ),
    ]
