# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-24 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0020_auto_20180704_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='pnode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cloud.Step', verbose_name='父节点'),
        ),
    ]
