# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-26 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0022_script_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='预案类型'),
        ),
    ]
