# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-26 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0023_process_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processrun',
            name='DataSet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.DataSet'),
        ),
    ]
