# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-06 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0025_script_succeedtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='run_reason',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='启动原因'),
        ),
    ]
