# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-31 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0025_script_succeedtest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='succeedtest',
            new_name='succeedtext',
        ),
    ]
